server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb+srv://spring-mongo:JrhMyBJXGEmfR86c@practicamongogrupal.fro0lfs.mongodb.net/bookings
      auto-index-creation: true
